baseURL = "/"
languageCode = "en-us"
title = "Tiacxy 3D Printer"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "This is another CoreXY 3D printer build"
  facebook = "https://www.facebook.com/tiacxy"
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/ismangil/tiacxy-3dprinter"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
